# Linear Algebra with SciPy

In [3]:
import numpy as np
import scipy.linalg as la

## Matrix Operations and Functions

*Multiplication* $A \times A$

*Arithmetic* $2I + 3A - AB$

*M Power* $mpow(A,3)$ OR $A@A@A$

*Transpose(.T)* $AA^T$

*Determinant* $\begin{vmatrix} 1 & 3 \\ -1 & 7 \end{vmatrix}$ `scipy.linalg.det`

*Inverse* $A^-1$ `scipy.linalg.inv`



In [6]:
A = np.array([[1,3],[-1,7]])
B = np.array([[5,2],[1,2]])
print(A,'\n\n', B)

print('\n----- Matrix Multiplication ------- ')
print(A@A) # @ = Multiplication

# Identity Matrix of size 2
I = np.eye(2)

print('\n----- Arithmetic ------- ')
print(2*I + 3*A - A@B)

from numpy.linalg import matrix_power as mpow

print('\n----- Powers ------- ')
print(mpow(A, 3)) # == print(A@A@A)

print('\n----- Transpose ------- ')
print(A@A.T)

print('\n----- Determinant ------- ')
print(la.det(A))

print('\n----- Inverse ------- ')
print(la.inv(A))

[[ 1  3]
 [-1  7]] 

 [[5 2]
 [1 2]]

----- Matrix Multiplication ------- 
[[-2 24]
 [-8 46]]

----- Arithmetic ------- 
[[-3.  1.]
 [-5. 11.]]

----- Powers ------- 
[[-26 162]
 [-54 298]]

----- Transpose ------- 
[[10 20]
 [20 50]]

----- Determinant ------- 
10.0

----- Inverse ------- 
[[ 0.7 -0.3]
 [ 0.1  0.1]]


### Dot vs Inner

In [10]:
print(A,'\n\n', B)
print('\n----- A dot B ------- ')
print(np.dot(A,B))

print('\n----- A inner B ------- ')
print(np.inner(A,B))

[[ 1  3]
 [-1  7]] 

 [[5 2]
 [1 2]]

----- A dot B ------- 
[[ 8  8]
 [ 2 12]]

----- A inner B ------- 
[[11  7]
 [ 9 13]]


---