# Numpy

- Homogenous Multi-dimensional Array
- indexed by a tuple of non-negative integers.
- Dimensiona : axes
- Numpy array : ndarray $&$ numpy.array $\ne$ array.array (SPLclass)

In [2]:
import numpy as np

# Info( Docstring ) Constructor ( Uncomment the following line )
# ?np.array

## N-d array Object

- Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).
- Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types.

![](./assets/ndarray.jpg)

**Important attributes**

- *ndarray.ndim :* Number of axes.
- *ndarray.shape:* Integer Tuple with size of array in each Dimension.
- *ndarray.size:* Total number of elements in the array
- *ndarray.dtype:* An object descritbing the types of elements of the array
- *ndarray.itemsize:* The size in bytes of each element of the array.
- *ndarray.data*

In [3]:
_matrix = np.arange(30).reshape(2,3,5)

print('Matrix :\n', _matrix)
print('\nShape :', _matrix.shape)
print('\nSize :', _matrix.size)
print('\nNo. of Dim. :', _matrix.ndim)
print('\nDtype :', _matrix.dtype.name)
print('\nItemSize :', _matrix.itemsize)
print('\nMemory Loc.:', _matrix.data)

Matrix :
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

Shape : (2, 3, 5)

Size : 30

No. of Dim. : 3

Dtype : int64

ItemSize : 8

Memory Loc.: <memory at 0x7ff3b8490c50>


In [4]:
# Creating 1D Numpy Array

a = np.array([1,2,3,4,5])

def print_matrix_info(x):
    print('Dimension :', x.ndim)
    print('Shape :', x.shape)    #Tuple
    print('Size :', x.size)
    print('---------')
    return x
    
print(print_matrix_info(a))

Dimension : 1
Shape : (5,)
Size : 5
---------
[1 2 3 4 5]


In [5]:
# Creating 2D Numpy Array

A = np.array([[1,2],[3,4],[5,6]])

print(print_matrix_info(A))


# Selecting Row or Column of 2D NPA

col = A[:,0]

column_as_2d_vector = col.reshape(3,1)

print('\n------------- Col ---------------')
print(print_matrix_info(col))

print('\n------- 2D Col. Vector ----------')
print(print_matrix_info(column_as_2d_vector))

Dimension : 2
Shape : (3, 2)
Size : 6
---------
[[1 2]
 [3 4]
 [5 6]]

------------- Col ---------------
Dimension : 1
Shape : (3,)
Size : 3
---------
[1 3 5]

------- 2D Col. Vector ----------
Dimension : 2
Shape : (3, 1)
Size : 3
---------
[[1]
 [3]
 [5]]


In [16]:
rank_2_array = np.array([
    [1, 2, 3, 4, 5],   # first row
    [6, 7, 8, 9, 10]   # second row
])

print('rank_2_array:\n', rank_2_array)
print('Shape:', rank_2_array.shape)
print('Number of rows:', rank_2_array.shape[0])  # Shape of first axis
print('Number of columns:', rank_2_array.shape[1])  # Shape of second axis

rank_2_array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Number of rows: 2
Number of columns: 5


## Data Types

`numpy.dtype(object, align, copy)`

### Built-in Types with Character code

    'b' − boolean

    'i' − (signed) integer

    'u' − unsigned integer

    'f' − floating-point

    'c' − complex-floating point

    'm' − timedelta

    'M' − datetime

    'O' − (Python) objects

    'S', 'a' − (byte-)string

    'U' − Unicode

    'V' − raw data (void)


In [6]:
#int8, int16, int32, int64 : equivalent string 'i1', 'i2','i4', etc. 

print('\nDtype:', np.dtype('i4'))
print('\nDtype:', np.dtype([('age',np.int8)]))


dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print('--------------------\n',a)


student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
b = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print('--------------------\n',b)


Dtype: int32

Dtype: [('age', 'i1')]
--------------------
 [(10,) (20,) (30,)]
--------------------
 [(b'abc', 21, 50.) (b'xyz', 18, 75.)]


## Common Matrices

In [17]:
# Defining common matrices

array_a = (3,3) # Defining Empty spaceholder matrix

print('\nZero:\n', np.zeros(array_a))
print('\nOnes:\n', np.ones(array_a))
print('\nIdentity:\n', np.eye(array_a[0]))
print('\nConstant:\n', np.full(array_a, 5))


Zero:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Constant:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


# Numpy Create

In [48]:
# Numpy form ranges

start, end, no_of_samples = 1,10,10
print('\nEvenlySpacedArrray:\n', np.linspace(start,end,no_of_samples))
print('\nEvenlySpacedArrray(in Log space):\n', np.logspace(start,end,no_of_samples, base=2))

start, end, step = 0,5,0.5 # step exclusive )
print('\nEvenlySpacedArrray:\n', np.arange(start,end,step))



EvenlySpacedArrray:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

EvenlySpacedArrray(in Log space):
 [   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]

EvenlySpacedArrray:
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [53]:
s_d = 1
array_shape = (3,3)

print('\nDrawn From Gaussian:\n',np.random.normal(scale=s_d, size= array_shape))
print('\nDrawn From SND:\n',np.random.randn(*array_shape))

seed_random = 2

print('\n Random Drawn From Gaussian:\n',np.random.seed(seed_random))
print('\nDrawn From SND:\n',np.random.randn(*array_shape))


Drawn From Gaussian:
 [[ 0.20420798  1.40669624 -1.7379595 ]
 [ 1.04082395  0.38047197 -0.21713527]
 [ 1.1735315  -2.34360319  1.16152149]]

Drawn From SND:
 [[ 0.38607805 -1.13313327  0.43309255]
 [-0.30408644  2.58529487  1.83533272]
 [ 0.44068987 -0.71925384 -0.58341459]]

 Random Drawn From Gaussian:
 None

Drawn From SND:
 [[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]
 [ 0.50288142 -1.24528809 -1.05795222]]


In [41]:
# Numpy from existing data

x = [1,2,3]
y = (4,5,6)
s = b'Hello World'
it = iter(range(5))  

print('\nArray Type:', type(np.asarray(x))) 
print('\nArray Type:', type(np.asarray(y))) 
print('\nFrom Buffer:', np.frombuffer(s, dtype = 'S1'))
print('\nFrom Iter:',np.fromiter(it, dtype = float)) # use iterator to create ndarray


Array Type: <class 'numpy.ndarray'>

Array Type: <class 'numpy.ndarray'>

From Buffer: [b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']

From Iter: [0. 1. 2. 3. 4.]


# Arithmetics

In [69]:
a = np.arange(3, dtype = np.float_).reshape(1,3)
b = np.array([10,10,10])
print(a,'\n\n',b)
print('\nAdd:\n', a+b) # np.sum(first_array, second_array)
print('\nSub:\n', a-b) # np.subtract(first_array, second_array)
print('\nMul:\n', a*b) # np.multiply(first_array, second_array) - Element wise
print('\nDiv:\n', a/b) # np.divide(first_array, second_array)
print('\nSum of Array b:\n', b.sum())

[[0. 1. 2.]] 

 [10 10 10]

Add:
 [[10. 11. 12.]]

Sub:
 [[-10.  -9.  -8.]]

Mul:
 [[ 0. 10. 20.]]

Div:
 [[0.  0.1 0.2]]

Sum of Array b:
 30


## Indexing and Slicing

In [96]:
a = np.arange(10) #[0 1 2 3 4 5 6 7 8 9]

print('\nIndex 4:\n',a[4])
print('\nSliced:\n',a[2:7:2]) # or a[slice(2,7,2)]
# print(a[2:])
# print(a[2:5]) # exclusive ]

b = np.array([[1,2,3],[3,4,5],[4,5,6]])

print('\nb:\n',b)
print('\nElement at index [1][2]:', b[1, 2])
print('\nb-Sliced:\n',b[1:])
print('\nb-Col-2:\n',b[...,1])
print('\nb-Row-2:\n',b[1,...])
print('\nb-Col-2 Onwards:\n',b[...,1:])


Index 4:
 4

Sliced:
 [2 4 6]

b:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]

Element at index [1][2]: 5

b-Sliced:
 [[3 4 5]
 [4 5 6]]

b-Col-2:
 [2 4 5]

b-Row-2:
 [3 4 5]

b-Col-2 Onwards:
 [[2 3]
 [4 5]
 [5 6]]


# Todo

- [ ] Integer and Boolean indexing
- [ ] Broadcasting
- [ ] Iterating over array
- [ ] Manipulation of Arrays
- [ ] Operations and Functions

[Numpy References](https://numpy.org/doc/1.19/reference/index.html)

---